### PR TITLE
feat: cluster icons

### PR DESCRIPTION
**Pull request by lundeeell**

### CODE REVIEW

**Comment by Graborg** [comment]
Looks great, but crashes when I click the clustered icon. I really don't know what the expected behaviour is here... but rather if it didn't crash 👯 
Also, the icons seem to have gotten a lot bigger now... not sure if intentional or if @lundeeell just needs new glasses.

**Review by Graborg — CHANGES_REQUESTED** [review]
^

**Comment by lundeeell** [comment]
@Graborg Fixed! And yes, icons are bigger 🤓

**Review by Graborg — APPROVED** [review]
Nice. An extra nice would be if the "clickable"-cursor does not even when it's a cluster, since now you get the feeling that it's clickable, only nothing happens.
But will approve!

**Pull request merged**
