### PR TITLE
feat: durable rabbitmq

### PR DESCRIPTION
**Pull request by raduachim**
- change rabbitmq to statefulset and configure the data path
- change exchanges and queues to be durable
- publish messages with persistent

Not the easiest to test.
I've tested it on the `predictivemovement-dev` namespace in the k8s cluster and the test was to change from Deployment to a StatefulSet then create a booking while the engine was not running ( so that it doesn't get consumed )
I've restarted the rabbitmq statefulset to see that the queues are still present on restart and the message for the booking was still in the queue

Before running it locally run
```bash
docker-compose stop && \
docker rm $(docker ps -aq --filter="name=predictivemovement_rabbitmq_1") && \
docker-compose build
```

### CODE REVIEW

**Review by Graborg — CHANGES_REQUESTED** [review]
Good, however, some queues are not set as durable in the engine, such as 
dispatch_offers
calculate_route_optimization 
delete_booking_from_engine 
delete_vehicle_from_engine
update_booking_status_in_engine

**Comment by Graborg** [comment]
Which means that if the engine is started first (before the engine-server), the queues will remain as not durable.

**Comment by raduachim** [comment]
> Good, however, some queues are not set as durable in the engine, such as
> dispatch_offers
> calculate_route_optimization
> delete_booking_from_engine
> delete_vehicle_from_engine
> update_booking_status_in_engine

nice find

**Review by Graborg — APPROVED** [review]
Perfect!

**Pull request merged**
